# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: mybuild-pipeline
      source: mybuild
    

pool:
  vmImage: ubuntu-latest

jobs:
  - deployment: Deploy
    displayName: build VM
    environment: 
      name: stg
      resourceType: VirtualMachine
    strategy:
     runOnce:
       deploy:
        steps:
 #         - download: mybuid-pipeline
#            artifact: drop
 #         - task: ExtractFiles@1
 #           inputs:
 #             archiveFilePatterns: '$(PIPELINE.WORKSPACE)/mybuild-pipeline/drop/$(resources.pipelines.mybuild-pipeline.runID).zip'
 #             destinationFolder: '$(agent.builddirectory)'
 #             cleanDestinationFolder: false
          - script: echo "Hello world"
             
          